package com.mitenewworld.datagen;
import com.mitenewworld.MITENewWorld;

import com.mitenewworld.registry.ModBlocks;
import com.mitenewworld.item.ModFoodItems;
import com.mitenewworld.registry.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class ModENUSLanProvider extends FabricLanguageProvider {
    public ModENUSLanProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput,"en_us", registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup registryLookup, TranslationBuilder translationBuilder) {
       /* translationBuilder.add("item.mitenewworld.tool.durability", "Durability");
        translationBuilder.add("item.mitenewworld.tool.foodlevel", "Food Level");
        translationBuilder.add("item.mitenewworld.tool.saturationlevel", "Saturation Level");
        translationBuilder.add(ModItems.COPPER_SWORD, "Copper Sword");
        translationBuilder.add(ModItems.SILVER_SWORD, "Silver Sword");
        translationBuilder.add(ModItems.GOLD_SWORD, "Gold Sword");
        translationBuilder.add(ModItems.IRON_SWORD, "Iron Sword");
        translationBuilder.add(ModItems.RUSTED_IRON_SWORD, "Rusted Iron Sword");
        translationBuilder.add(ModItems.MITHRIL_SWORD, "Mithril Sword");
        translationBuilder.add(ModItems.ANCIENT_METAL_SWORD, "Ancient Metal Sword");
        translationBuilder.add(ModItems.ADAMANTIUM_SWORD, "Adamantium Metal Sword");
        translationBuilder.add(ModItems.COPPER_DAGGER, "Copper Dagger");
        translationBuilder.add(ModItems.SILVER_DAGGER, "Silver Dagger");
        translationBuilder.add(ModItems.GOLD_DAGGER, "Gold Dagger");
        translationBuilder.add(ModItems.IRON_DAGGER, "Iron Dagger");
        translationBuilder.add(ModItems.RUSTED_IRON_DAGGER, "Rusted Iron Dagger");
        translationBuilder.add(ModItems.MITHRIL_DAGGER, "Mithril Dagger");
        translationBuilder.add(ModItems.ANCIENT_METAL_DAGGER, "Ancient Metal Dagger");
        translationBuilder.add(ModItems.ADAMANTIUM_DAGGER, "Adamantium Metal Dagger");
        translationBuilder.add(ModItems.COPPER_BATTLEAXE, "Copper Battleaxe");
        translationBuilder.add(ModItems.SILVER_BATTLEAXE, "Silver Battleaxe");
        translationBuilder.add(ModItems.GOLD_BATTLEAXE, "Gold Battleaxe");
        translationBuilder.add(ModItems.IRON_BATTLEAXE, "Iron Battleaxe");
        translationBuilder.add(ModItems.RUSTED_IRON_BATTLEAXE, "Rusted Iron Battleaxe");
        translationBuilder.add(ModItems.MITHRIL_BATTLEAXE, "Mithril Battleaxe");
        translationBuilder.add(ModItems.ANCIENT_METAL_BATTLEAXE, "Ancient Metal Battleaxe");
        translationBuilder.add(ModItems.ADAMANTIUM_BATTLEAXE, "Adamantium Metal Battleaxe");
        translationBuilder.add(ModItems.COPPER_WARHAMMER, "Copper Warhammer");
        translationBuilder.add(ModItems.SILVER_WARHAMMER, "Silver Warhammer");
        translationBuilder.add(ModItems.GOLD_WARHAMMER, "Gold Warhammer");
        translationBuilder.add(ModItems.IRON_WARHAMMER, "Iron Warhammer");
        translationBuilder.add(ModItems.RUSTED_IRON_WARHAMMER, "Rusted Iron Warhammer");
        translationBuilder.add(ModItems.MITHRIL_WARHAMMER, "Mithril Warhammer");
        translationBuilder.add(ModItems.ANCIENT_METAL_WARHAMMER, "Ancient Metal Warhammer");
        translationBuilder.add(ModItems.ADAMANTIUM_WARHAMMER, "Adamantium Metal Warhammer");
        translationBuilder.add(ModItems.COPPER_SCYTHE, "Copper Scythe");
        translationBuilder.add(ModItems.SILVER_SCYTHE, "Silver Scythe");
        translationBuilder.add(ModItems.GOLD_SCYTHE, "Gold Scythe");
        translationBuilder.add(ModItems.IRON_SCYTHE, "Iron Scythe");
        translationBuilder.add(ModItems.RUSTED_IRON_SCYTHE, "Rusted Iron Scythe");
        translationBuilder.add(ModItems.MITHRIL_SCYTHE, "Mithril Scythe");
        translationBuilder.add(ModItems.ANCIENT_METAL_SCYTHE, "Ancient Metal Scythe");
        translationBuilder.add(ModItems.ADAMANTIUM_SCYTHE, "Adamantium Metal Scythe");
        translationBuilder.add(ModItems.COPPER_SHOVEL, "Copper Shovel");
        translationBuilder.add(ModItems.SILVER_SHOVEL, "Silver Shovel");
        translationBuilder.add(ModItems.RUSTED_IRON_SHOVEL, "Rusted Iron Shovel");
        translationBuilder.add(ModItems.IRON_SHOVEL, "Iron Shovel");
        translationBuilder.add(ModItems.GOLD_SHOVEL, "Gold Shovel");
        translationBuilder.add(ModItems.OBSIDIAN_SHOVEL, "Obsidian Shovel");
        translationBuilder.add(ModItems.FLINT_SHOVEL, "Flint Shovel");
        translationBuilder.add(ModItems.MITHRIL_SHOVEL, "Mithril Shovel");
        translationBuilder.add(ModItems.ANCIENT_METAL_SHOVEL, "Ancient Metal Shovel");
        translationBuilder.add(ModItems.ADAMANTIUM_SHOVEL, "Adamantium Metal Shovel");
        translationBuilder.add(ModItems.COPPER_PICKAXE, "Copper Pickaxe");
        translationBuilder.add(ModItems.SILVER_PICKAXE, "Silver Pickaxe");
        translationBuilder.add(ModItems.GOLD_PICKAXE, "Gold Pickaxe");
        translationBuilder.add(ModItems.RUSTED_IRON_PICKAXE, "Rusted Iron Pickaxe");
        translationBuilder.add(ModItems.IRON_PICKAXE, "Iron Pickaxe");
        translationBuilder.add(ModItems.MITHRIL_PICKAXE, "Mithril Pickaxe");
        translationBuilder.add(ModItems.ANCIENT_METAL_PICKAXE, "Ancient Metal Pickaxe");
        translationBuilder.add(ModItems.ADAMANTIUM_PICKAXE, "Adamantium Metal Pickaxe");
        translationBuilder.add(ModItems.COPPER_AXE, "Copper Axe");
        translationBuilder.add(ModItems.SILVER_AXE, "Silver Axe");
        translationBuilder.add(ModItems.GOLD_AXE, "Gold Axe");
        translationBuilder.add(ModItems.FLINT_AXE, "Flint Axe");
        translationBuilder.add(ModItems.OBSIDIAN_AXE, "Obsidian Axe");
        translationBuilder.add(ModItems.RUSTED_IRON_AXE, "Rusted Iron Axe");
        translationBuilder.add(ModItems.IRON_AXE, "Iron Axe");
        translationBuilder.add(ModItems.MITHRIL_AXE, "Mithril Axe");
        translationBuilder.add(ModItems.ANCIENT_METAL_AXE, "Ancient Metal Axe");
        translationBuilder.add(ModItems.ADAMANTIUM_AXE, "Adamantium Metal Axe");
        translationBuilder.add(ModItems.COPPER_HOE, "Copper Hoe");
        translationBuilder.add(ModItems.SILVER_HOE, "Silver Hoe");
        translationBuilder.add(ModItems.GOLD_HOE, "Gold Hoe");
        translationBuilder.add(ModItems.RUSTED_IRON_HOE, "Rusted Iron Hoe");
        translationBuilder.add(ModItems.IRON_HOE, "Iron Hoe");
        translationBuilder.add(ModItems.MITHRIL_HOE, "Mithril Hoe");
        translationBuilder.add(ModItems.ANCIENT_METAL_HOE, "Ancient Metal Hoe");
        translationBuilder.add(ModItems.ADAMANTIUM_HOE, "Adamantium Metal Hoe");
        translationBuilder.add(ModItems.COPPER_MATTOCK, "Copper Mattock");
        translationBuilder.add(ModItems.SILVER_MATTOCK, "Silver Mattock");
        translationBuilder.add(ModItems.GOLD_MATTOCK, "Gold Mattock");
        translationBuilder.add(ModItems.RUSTED_IRON_MATTOCK, "Rusted Iron Mattock");
        translationBuilder.add(ModItems.IRON_MATTOCK, "Iron Mattock");
        translationBuilder.add(ModItems.MITHRIL_MATTOCK, "Mithril Mattock");
        translationBuilder.add(ModItems.ANCIENT_METAL_MATTOCK, "Ancient Metal Mattock");
        translationBuilder.add(ModItems.ADAMANTIUM_MATTOCK, "Adamantium Metal Mattock");
        translationBuilder.add(ModItems.FLINT_HATCHET, "Flint Hatchet");
        translationBuilder.add(ModItems.COPPER_HATCHET, "Copper Hatchet");
        translationBuilder.add(ModItems.SILVER_HATCHET, "Silver Hatchet");
        translationBuilder.add(ModItems.GOLD_HATCHET, "Gold Hatchet");
        translationBuilder.add(ModItems.RUSTED_IRON_HATCHET, "Rusted Iron Hatchet");
        translationBuilder.add(ModItems.IRON_HATCHET, "Iron Hatchet");
        translationBuilder.add(ModItems.MITHRIL_HATCHET, "Mithril Hatchet");
        translationBuilder.add(ModItems.ANCIENT_METAL_HATCHET, "Ancient Metal Hatchet");
        translationBuilder.add(ModItems.ADAMANTIUM_HATCHET, "Adamantium Metal Hatchet");
        translationBuilder.add(ModItems.COPPER_SHEARS, "Copper Shears");
        translationBuilder.add(ModItems.SILVER_SHEARS, "Silver Shears");
        translationBuilder.add(ModItems.GOLD_SHEARS, "Gold Shears");
        translationBuilder.add(ModItems.RUSTED_IRON_SHEARS, "Rusted Iron Shears");
        translationBuilder.add(ModItems.IRON_SHEARS, "Iron Shears");
        translationBuilder.add(ModItems.MITHRIL_SHEARS, "Mithril Shears");
        translationBuilder.add(ModItems.ANCIENT_METAL_SHEARS, "Ancient Metal Shears");
        translationBuilder.add(ModItems.ADAMANTIUM_SHEARS, "Adamantium Metal Shears");
        translationBuilder.add(ModItems.FLINT_KNIFE, "Flint Knife");
        translationBuilder.add(ModItems.COPPER_BUCKET, "Copper Bucket");
        translationBuilder.add(ModItems.SILVER_BUCKET, "Silver Bucket");
        translationBuilder.add(ModItems.GOLD_BUCKET, "Gold Bucket");
        translationBuilder.add(ModItems.IRON_BUCKET, "Iron Bucket");
        translationBuilder.add(ModItems.MITHRIL_BUCKET, "Mithril Bucket");
        translationBuilder.add(ModItems.ANCIENT_METAL_BUCKET, "Ancient Metal Bucket");
        translationBuilder.add(ModItems.ADAMANTIUM_BUCKET, "Adamantium Metal Bucket");
        translationBuilder.add(ModItems.WATER_COPPER_BUCKET, "Water Copper Bucket");
        translationBuilder.add(ModItems.WATER_SILVER_BUCKET, "Water Silver Bucket");
        translationBuilder.add(ModItems.WATER_GOLD_BUCKET, "Water Gold Bucket");
        translationBuilder.add(ModItems.WATER_IRON_BUCKET, "Water Iron Bucket");
        translationBuilder.add(ModItems.WATER_MITHRIL_BUCKET, "Water Mithril Bucket");
        translationBuilder.add(ModItems.WATER_ANCIENT_METAL_BUCKET, "Water Ancient Metal Bucket");
        translationBuilder.add(ModItems.WATER_ADAMANTIUM_BUCKET, "Water Adamantium Metal Bucket");
        translationBuilder.add(ModItems.LAVA_COPPER_BUCKET, "Lava Copper Bucket");
        translationBuilder.add(ModItems.LAVA_SILVER_BUCKET, "Lava Silver Bucket");
        translationBuilder.add(ModItems.LAVA_GOLD_BUCKET, "Lava Gold Bucket");
        translationBuilder.add(ModItems.LAVA_IRON_BUCKET, "Lava Iron Bucket");
        translationBuilder.add(ModItems.LAVA_MITHRIL_BUCKET, "Lava Mithril Bucket");
        translationBuilder.add(ModItems.LAVA_ANCIENT_METAL_BUCKET, "Lava Ancient Metal Bucket");
        translationBuilder.add(ModItems.LAVA_ADAMANTIUM_BUCKET, "Lava Adamantium Metal Bucket");
        translationBuilder.add(ModItems.STONE_COPPER_BUCKET, "Stone Copper Bucket");
        translationBuilder.add(ModItems.STONE_SILVER_BUCKET, "Stone Silver Bucket");
        translationBuilder.add(ModItems.STONE_GOLD_BUCKET, "Stone Gold Bucket");
        translationBuilder.add(ModItems.STONE_IRON_BUCKET, "Stone Iron Bucket");
        translationBuilder.add(ModItems.STONE_MITHRIL_BUCKET, "Stone Mithril Bucket");
        translationBuilder.add(ModItems.STONE_ANCIENT_METAL_BUCKET, "Stone Ancient Metal Bucket");
        translationBuilder.add(ModItems.STONE_ADAMANTIUM_BUCKET, "Stone Adamantium Metal Bucket");
        translationBuilder.add(ModFoodItems.SALAD, "Salad");
        translationBuilder.add(ModFoodItems.PORRIDGE, "Porridge");
        translationBuilder.add(ModFoodItems.BOWL_OF_MILK, "Bowl of Milk");
        translationBuilder.add(ModFoodItems.CEREAL, "Cereal");
        translationBuilder.add(ModFoodItems.PUMPKIN_SOUP, "Pumpkin Soup");
        translationBuilder.add(ModFoodItems.CREAM_OF_MUSHROOM_SOUP, "Cream of Mushroom Soup");
        translationBuilder.add(ModFoodItems.VEGETABLE_SOUP, "Vegetable Soup");
        translationBuilder.add(ModFoodItems.CHICKEN_SOUP, "Chicken Soup");
        translationBuilder.add(ModFoodItems.BEEF_STEW, "Beef Stew");
        translationBuilder.add(ModFoodItems.SORBET, "Sorbet");
        translationBuilder.add(ModFoodItems.MASHED_POTATO, "Mashed Potato");
        translationBuilder.add(ModFoodItems.ICE_CREAM, "Ice Cream");
        translationBuilder.add(ModFoodItems.BLUE_BERRIES, "Blue Berries");
        translationBuilder.add(ModFoodItems.CHOCOLATE, "Chocolate");
        translationBuilder.add(ModFoodItems.ONION, "Onion");
        translationBuilder.add(ModFoodItems.ORANGE, "Orange");
        translationBuilder.add(ModFoodItems.CHEESE, "Cheese");
        translationBuilder.add(ModFoodItems.DOUGH, "Dough");
        translationBuilder.add(ModFoodItems.BANANA, "Banana");
        translationBuilder.add(ModFoodItems.MILK_COPPER_BUCKET, "Milk Copper Bucket");
        translationBuilder.add(ModFoodItems.MILK_SILVER_BUCKET, "Milk Silver Bucket");
        translationBuilder.add(ModFoodItems.MILK_GOLD_BUCKET, "Milk Gold Bucket");
        translationBuilder.add(ModFoodItems.MILK_IRON_BUCKET, "Milk Iron Bucket");
        translationBuilder.add(ModFoodItems.MILK_MITHRIL_BUCKET, "Milk Mithril Bucket");
        translationBuilder.add(ModFoodItems.MILK_ANCIENT_METAL_BUCKET, "Milk Ancient Metal Bucket");
        translationBuilder.add(ModFoodItems.MILK_ADAMANTIUM_BUCKET, "Milk Adamantium Bucket");
        translationBuilder.add(ModFoodItems.WATER_BOWL, "Water Bowl");
        translationBuilder.add(ModFoodItems.HORSE_MEAT, "Horse Meat");
        translationBuilder.add(ModItems.COPPER_HELMET, "Copper Helmet");
        translationBuilder.add(ModItems.COPPER_CHESTPLATE, "Copper Chestplate");
        translationBuilder.add(ModItems.COPPER_LEGGINGS, "Copper Leggings");
        translationBuilder.add(ModItems.COPPER_BOOTS, "Copper Boots");
        translationBuilder.add(ModItems.COPPER_CHAIN_HELMET, "Copper Chain Helmet");
        translationBuilder.add(ModItems.COPPER_CHAIN_CHESTPLATE, "Copper Chain Chestplate");
        translationBuilder.add(ModItems.COPPER_CHAIN_LEGGINGS, "Copper Chain Leggings");
        translationBuilder.add(ModItems.COPPER_CHAIN_BOOTS, "Copper Chain Boots");
        translationBuilder.add(ModItems.SILVER_HELMET, "Silver Helmet");
        translationBuilder.add(ModItems.SILVER_CHESTPLATE, "Silver Chestplate");
        translationBuilder.add(ModItems.SILVER_LEGGINGS, "Silver Leggings");
        translationBuilder.add(ModItems.SILVER_BOOTS, "Silver Boots");
        translationBuilder.add(ModItems.SILVER_CHAIN_HELMET, "Silver Chain Helmet");
        translationBuilder.add(ModItems.SILVER_CHAIN_CHESTPLATE, "Silver Chain Chestplate");
        translationBuilder.add(ModItems.SILVER_CHAIN_LEGGINGS, "Silver Chain Leggings");
        translationBuilder.add(ModItems.SILVER_CHAIN_BOOTS, "Silver Chain Boots");
        translationBuilder.add(ModItems.GOLD_HELMET, "Gold Helmet");
        translationBuilder.add(ModItems.GOLD_CHESTPLATE, "Gold Chestplate");
        translationBuilder.add(ModItems.GOLD_LEGGINGS, "Gold Leggings");
        translationBuilder.add(ModItems.GOLD_BOOTS, "Gold Boots");
        translationBuilder.add(ModItems.GOLD_CHAIN_HELMET, "Gold Chain Helmet");
        translationBuilder.add(ModItems.GOLD_CHAIN_CHESTPLATE, "Gold Chain Chestplate");
        translationBuilder.add(ModItems.GOLD_CHAIN_LEGGINGS, "Gold Chain Leggings");
        translationBuilder.add(ModItems.GOLD_CHAIN_BOOTS, "Gold Chain Boots");
        translationBuilder.add(ModItems.RUSTED_IRON_HELMET, "Rusted Iron Helmet");
        translationBuilder.add(ModItems.RUSTED_IRON_CHESTPLATE, "Rusted Iron Chestplate");
        translationBuilder.add(ModItems.RUSTED_IRON_LEGGINGS, "Rusted Iron Leggings");
        translationBuilder.add(ModItems.RUSTED_IRON_BOOTS, "Rusted Iron Boots");
        translationBuilder.add(ModItems.RUSTED_IRON_CHAIN_HELMET, "Rusted Iron Chain Helmet");
        translationBuilder.add(ModItems.RUSTED_IRON_CHAIN_CHESTPLATE, "Rusted Iron Chain Chestplate");
        translationBuilder.add(ModItems.RUSTED_IRON_CHAIN_LEGGINGS, "Rusted Iron Chain Leggings");
        translationBuilder.add(ModItems.RUSTED_IRON_CHAIN_BOOTS, "Rusted Iron Chain Boots");
        translationBuilder.add(ModItems.IRON_HELMET, "Iron Helmet");
        translationBuilder.add(ModItems.IRON_CHESTPLATE, "Iron Chestplate");
        translationBuilder.add(ModItems.IRON_LEGGINGS, "Iron Leggings");
        translationBuilder.add(ModItems.IRON_BOOTS, "Iron Boots");
        translationBuilder.add(ModItems.IRON_CHAIN_HELMET, "Iron Chain Helmet");
        translationBuilder.add(ModItems.IRON_CHAIN_CHESTPLATE, "Iron Chain Chestplate");
        translationBuilder.add(ModItems.IRON_CHAIN_LEGGINGS, "Iron Chain Leggings");
        translationBuilder.add(ModItems.IRON_CHAIN_BOOTS, "Iron Chain Boots");
        translationBuilder.add(ModItems.MITHRIL_HELMET, "Mithril Helmet");
        translationBuilder.add(ModItems.MITHRIL_CHESTPLATE, "Mithril Chestplate");
        translationBuilder.add(ModItems.MITHRIL_LEGGINGS, "Mithril Leggings");
        translationBuilder.add(ModItems.MITHRIL_BOOTS, "Mithril Boots");
        translationBuilder.add(ModItems.MITHRIL_CHAIN_HELMET, "Mithril Chain Helmet");
        translationBuilder.add(ModItems.MITHRIL_CHAIN_CHESTPLATE, "Mithril Chain Chestplate");
        translationBuilder.add(ModItems.MITHRIL_CHAIN_LEGGINGS, "Mithril Chain Leggings");
        translationBuilder.add(ModItems.MITHRIL_CHAIN_BOOTS, "Mithril Chain Boots");
        translationBuilder.add(ModItems.ANCIENT_METAL_HELMET, "Ancient Metal Helmet");
        translationBuilder.add(ModItems.ANCIENT_METAL_CHESTPLATE, "Ancient Metal Chestplate");
        translationBuilder.add(ModItems.ANCIENT_METAL_LEGGINGS, "Ancient Metal Leggings");
        translationBuilder.add(ModItems.ANCIENT_METAL_BOOTS, "Ancient Metal Boots");
        translationBuilder.add(ModItems.ANCIENT_METAL_CHAIN_HELMET, "Ancient Metal Chain Helmet");
        translationBuilder.add(ModItems.ANCIENT_METAL_CHAIN_CHESTPLATE, "Ancient Metal Chain Chestplate");
        translationBuilder.add(ModItems.ANCIENT_METAL_CHAIN_LEGGINGS, "Ancient Metal Chain Leggings");
        translationBuilder.add(ModItems.ANCIENT_METAL_CHAIN_BOOTS, "Ancient Metal Chain Boots");
        translationBuilder.add(ModItems.ADAMANTIUM_HELMET, "Adamantium Helmet");
        translationBuilder.add(ModItems.ADAMANTIUM_CHESTPLATE, "Adamantium Chestplate");
        translationBuilder.add(ModItems.ADAMANTIUM_LEGGINGS, "Adamantium Leggings");
        translationBuilder.add(ModItems.ADAMANTIUM_BOOTS, "Adamantium Boots");
        translationBuilder.add(ModItems.ADAMANTIUM_CHAIN_HELMET, "Adamantium Chain Helmet");
        translationBuilder.add(ModItems.ADAMANTIUM_CHAIN_CHESTPLATE, "Adamantium Chain Chestplate");
        translationBuilder.add(ModItems.ADAMANTIUM_CHAIN_LEGGINGS, "Adamantium Chain Leggings");
        translationBuilder.add(ModItems.ADAMANTIUM_CHAIN_BOOTS, "Adamantium Chain Boots");
        translationBuilder.add(ModItems.FLINT_FRAGMENT, "Flint Fragment");
        translationBuilder.add(ModItems.EMERALD_FRAGMENT, "Emerald Fragment");
        translationBuilder.add(ModItems.GLASS_FRAGMENT, "Glass Fragment");
        translationBuilder.add(ModItems.DIAMOND_FRAGMENT, "Diamond Fragment");
        translationBuilder.add(ModItems.NETHER_QUARTZ_FRAGMENT, "Nether Quartz Fragment");
        translationBuilder.add(ModItems.OBSIDIAN_FRAGMENT, "Obsidian Fragment");
        translationBuilder.add(ModItems.SINEW, "Sinew");
        translationBuilder.add(ModItems.COPPER_CHAIN, "Copper Chain");
        translationBuilder.add(ModItems.SILVER_CHAIN, "Silver Chain");
        translationBuilder.add(ModItems.GOLD_CHAIN, "Gold Chain");
        translationBuilder.add(ModItems.IRON_CHAIN, "Iron Chain");
        translationBuilder.add(ModItems.MITHRIL_CHAIN, "Mithril Chain");
        translationBuilder.add(ModItems.ANCIENT_METAL_CHAIN, "Ancient Metal Chain");
        translationBuilder.add(ModItems.ADAMANTIUM_CHAIN, "Adamantium Chain");
        translationBuilder.add(ModItems.RAW_COPPER, "Raw Copper");
        translationBuilder.add(ModItems.RAW_SILVER, "Raw Silver");
        translationBuilder.add(ModItems.RAW_GOLD, "Raw Gold");
        translationBuilder.add(ModItems.RAW_IRON, "Raw Iron");
        translationBuilder.add(ModItems.RAW_MITHRIL, "Raw Mithril");
        translationBuilder.add(ModItems.RAW_ADAMANTIUM, "Raw Adamantium");
        translationBuilder.add(ModItems.COPPER_INGOT, "Copper Ingot");
        translationBuilder.add(ModItems.SILVER_INGOT, "Silver Ingot");
        translationBuilder.add(ModItems.GOLD_INGOT, "Gold Ingot");
        translationBuilder.add(ModItems.IRON_INGOT, "Iron Ingot");
        translationBuilder.add(ModItems.MITHRIL_INGOT, "Mithril Ingot");
        translationBuilder.add(ModItems.ANCIENT_METAL_INGOT, "Ancient Metal Ingot");
        translationBuilder.add(ModItems.ADAMANTIUM_INGOT, "Adamantium Ingot");
        translationBuilder.add(ModItems.COPPER_NUGGET, "Copper Nugget");
        translationBuilder.add(ModItems.SILVER_NUGGET, "Silver Nugget");
        translationBuilder.add(ModItems.GOLD_NUGGET, "Gold Nugget");
        translationBuilder.add(ModItems.IRON_NUGGET, "Iron Nugget");
        translationBuilder.add(ModItems.MITHRIL_NUGGET, "Mithril Nugget");
        translationBuilder.add(ModItems.ANCIENT_METAL_NUGGET, "Ancient Metal Nugget");
        translationBuilder.add(ModItems.ADAMANTIUM_NUGGET, "Adamantium Nugget");
        translationBuilder.add(ModBlocks.COPPER_BLOCK, "Copper Block");
        translationBuilder.add(ModBlocks.SILVER_BLOCK, "Silver Block");
        translationBuilder.add(ModBlocks.GOLD_BLOCK, "Gold Block");
        translationBuilder.add(ModBlocks.IRON_BLOCK, "Iron Block");
        translationBuilder.add(ModBlocks.MITHRIL_BLOCK, "Mithril Block");
        translationBuilder.add(ModBlocks.ANCIENT_METAL_BLOCK, "Ancient Metal Block");
        translationBuilder.add(ModBlocks.ADAMANTIUM_BLOCK, "Adamantium Block");
        translationBuilder.add(ModBlocks.RAW_COPPER_BLOCK, "Raw Copper Block");
        translationBuilder.add(ModBlocks.RAW_SILVER_BLOCK, "Raw Silver Block");
        translationBuilder.add(ModBlocks.RAW_GOLD_BLOCK, "Raw Gold Block");
        translationBuilder.add(ModBlocks.RAW_IRON_BLOCK, "Raw Iron Block");
        translationBuilder.add(ModBlocks.RAW_MITHRIL_BLOCK, "Raw Mithril Block");
        translationBuilder.add(ModBlocks.RAW_ADAMANTIUM_BLOCK, "Raw Adamantium Block");
        translationBuilder.add(ModBlocks.GOLD_ORE_NETHERRACK, "not use");
        translationBuilder.add(ModBlocks.COAL_ORE, "Coal Ore");
        translationBuilder.add(ModBlocks.DEEPSLATE_COAL_ORE, "Deepslate Coal Ore");
        translationBuilder.add(ModBlocks.IRON_ORE, "Iron Ore");
        translationBuilder.add(ModBlocks.DEEPSLATE_IRON_ORE, "Deepslate Iron Ore");
        translationBuilder.add(ModBlocks.COPPER_ORE, "Copper Ore");
        translationBuilder.add(ModBlocks.DEEPSLATE_COPPER_ORE, "Deepslate Copper Ore");
        translationBuilder.add(ModBlocks.SILVER_ORE, "Silver Ore");
        translationBuilder.add(ModBlocks.DEEPSLATE_SILVER_ORE, "Deepslate Silver Ore");
        translationBuilder.add(ModBlocks.GOLD_ORE, "Gold Ore");
        translationBuilder.add(ModBlocks.DEEPSLATE_GOLD_ORE, "Deepslate Gold Ore");
        translationBuilder.add(ModBlocks.MITHRIL_ORE, "Mithril Ore");
        translationBuilder.add(ModBlocks.ADAMANTIUM_ORE, "Adamantium Ore");
        translationBuilder.add(ModBlocks.MOD_FLINT_CRAFTING_TABLE_BLOCK, "Flint Crafting Table");
        translationBuilder.add(ModBlocks.MOD_COPPER_CRAFTING_TABLE_BLOCK, "Copper Crafting Table");
        translationBuilder.add(ModBlocks.MOD_SILVER_CRAFTING_TABLE_BLOCK, "Silver Crafting Table");
        translationBuilder.add(ModBlocks.MOD_GOLD_CRAFTING_TABLE_BLOCK, "Gold Crafting Table");
        translationBuilder.add(ModBlocks.MOD_IRON_CRAFTING_TABLE_BLOCK, "Iron Crafting Table");
        translationBuilder.add(ModBlocks.MOD_MITHRIL_CRAFTING_TABLE_BLOCK, "Mithril Crafting Table");
        translationBuilder.add(ModBlocks.MOD_ANCIENT_METAL_CRAFTING_TABLE_BLOCK, "Ancient Metal Crafting Table");
        translationBuilder.add(ModBlocks.MOD_ADAMANTIUM_CRAFTING_TABLE_BLOCK, "Adamantium Crafting Table");
        translationBuilder.add(ModBlocks.MOD_CLAY_FURNACE_BLOCK, "Clay Furnace");
        translationBuilder.add(ModBlocks.MOD_LARGE_CLAY_FURNACE_BLOCK, "Large Clay Furnace");
        translationBuilder.add(ModBlocks.MOD_STONE_FURNACE_BLOCK, "Stone Furnace");
        translationBuilder.add(ModBlocks.MOD_SANDSTONE_FURNACE_BLOCK, "Sandstone Furnace");
        translationBuilder.add(ModBlocks.MOD_OBSIDIAN_FURNACE_BLOCK, "Obsidian Furnace");
        translationBuilder.add(ModBlocks.MOD_NETHERRACK_FURNACE_BLOCK, "Netherrack Furnace");











*/



    }
}
